apiVersion: v1
kind: Template
metadata:
  name: nexus-jos
objects:
# Sonatype Nexus
- apiVersion: v1
  kind: Service
  metadata:
    name: nexus
    annotations:
      description: Sonatype Nexus repository manager's http port
  spec:
    ports:
    - name: web
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      app: nexus
      deploymentconfig: nexus
      sessionAffinity: None
      type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    name: nexus
  spec:
    port:
      targetPort: web
    to:
      kind: Service
      name: nexus
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: nexus
  spec:
    tags:
    - annotations:
      description: The Nexus Docker image
      tags: nexus
      from:
        kind: DockerImage
        name: openshiftdemos/nexus:2.13.0-01
        importPolicy: {}
        name: "2.13.0-01"
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: nexus
  spec:
    replicas: 1
    selector:
      app: nexus
      deploymentconfig: nexus
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: nexus
          deploymentconfig: nexus
      spec:
        containers:
        - image: ' '
          imagePullPolicy: Always
          name: nexus
          ports:
          - containerPort: 8081
            protocol: TCP
            resources:
              limits:
                memory: 1Gi
            terminationMessagePath: /dev/termination-log
          volumeMounts:
            - mountPath: /opt/nexus-work
              name: nexus-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: nexus-data
  triggers:
  - type: ConfigChange
  - imageChangeParams:
    automatic: true
    containerNames:
    - nexus
    from:
      kind: ImageStreamTag
      name: nexus:2.13.0-01
    type: ImageChange
  status: {}